In [17]:
import numpy as np

In [21]:
list1=[1,2,3,4]
type(list1)

list

In [27]:
array1=np.array(list1)
array1

array([1, 2, 3, 4])

In [31]:
list2=[[1,2,3],[4,5,6],[7,8,9]]
list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [33]:
array2=np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
array3=np.arange(0,10,3)
array3

array([0, 3, 6, 9])

In [53]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## NumPy's linspace function


In [90]:
np.linspace(1,100,30)

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

In [92]:
np.linspace(1,100,30)

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

## Eye function
#### The eye function is a built-in function in NumPy that is used to create an identity matrix
An identity matrix is a type of matrix in which all the diagonal elements are one, and the remaining elements are zero



In [95]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

## NumPy's rand function 
to create an array with random numbers

In [99]:
np.random.rand(3)

array([0.46082249, 0.20109986, 0.31889847])

In [101]:
np.random.randn(3)

array([ 1.47394691,  0.78762207, -0.2048614 ])

In [146]:
np.random.randint(1,30,[2,3])

array([[ 2, 22, 20],
       [13,  5, 24]])

## NumPy indexing

In [150]:
arr_example=np.arange(1,11)
arr_example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [185]:
arr_example[3:5]=99

In [187]:
arr_example

array([ 1,  2,  3, 99, 99,  6,  7,  8,  9, 10])

In [189]:
arr_example1=np.random.randint(1,40,[3,3])
arr_example1

array([[33, 34, 31],
       [ 5, 11,  8],
       [ 2, 32, 23]])

In [170]:
arr_example1[1:3]

array([[11, 27, 26],
       [25, 35, 15]])

In [172]:
arr_example1[1][1:3]

array([27, 26])

##Task for you
### print the 35,15 number position

## NumPy operations